name: Auto Generate Image

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *" # Every hour at minute 30 to avoid workflow delays due to long queue times

jobs:
  send-http-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP POST request
        run: |
          curl -X POST "${{ vars.APP_HOST }}${{ vars.GEN_IMAGE_ENDPOINT }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.APP_API_KEY }}" \
            -d '{"json":{}}' \
            -o response.txt
